title: <title of the page>
email: <user email address>
description: >- # multiline description
  description line 1
  description line 2
  ...
  description line x
twitter_username: <username>
github_username: <username
minimal_mistakes_skin: default # options [air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise]
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "username"
  avatar : "/assets/images/bio-photo.png"
  bio    : ""
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: ""
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: ""
    - label: "Linkedin"
      icon: "fab fa-linkedin-in"
      url: ""

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: ""
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: ""
    - label: "Linkedin"
      icon: "fab fa-linkedin-in"
      url: ""

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  
  # _scripts
  - scope:
      path: "_scripts"
      type: pages
    values:
      layout: single
      author_profile: true
      
collections:
  scripts:
    output: true
    permalink: /:collection/:path/